### ISSUE TITLE
Cannot push images from other server

### ISSUE THREAD

**Issue by rcarrascoz** [distribution/distribution-library-image#163]
Hello, I pull registry, and I do test and it is working. So when I want to push some image from other server I cannot. The port 5000 between them are open, but when I make a push... look bellow:

Error response from daemon: Get "https://registry.server.es:5000/v2/": http: server gave HTTP response to HTTPS client

My tag it is:

registry.server.es:5000/image   24d37a46   ebxe8c6e4799   8 days ago      1.55GB

Do I need to make something different? I need to do a docker login? are ther any user and pass registry?
Thanks a lot,
Rafa.

**Comment by milosgajdos** [comment]
off the top of my head, you havent' setup your docker daemon to work with your registry e.g. something like this:

```
Insecure Registries:
 registry.server.es
```

Besides, please ask in https://github.com/distribution/distribution/discussions

This repository is concerned with the _container image_ not with the setup etc.

Closing.
