### ISSUE TITLE
There's something wrong with the image

### ISSUE THREAD

**Issue by hadmut** [distribution/distribution-library-image#165]
Hi, 

the last docker image I got from docker hub was

registry           <none>    9363667f8aec   2 months ago   25.4MB

(<none> because I already pulled latest) but after pull I get an older one?

registry           latest    d6b2c32a0f14   7 months ago   25.4MB

**Comment by milosgajdos** [comment]
Ask in docker/hub-feedback repository. Docker Hub has nothing to do with this repository -- it's a commercial offering of Docker inc.
