### ISSUE TITLE
Run a Registry as a pull-through cache for microsoft registry mcr.microsoft.com

### ISSUE THREAD

**Issue by ancindian** [distribution/distribution-library-image#174]
Hi Team:
     We are trying to set up registry as pull-through cache for our users for microsoft based images from mcr.microsoft.com
There are some issues (4 years older) that suggests that this isnt possible, https://github.com/microsoft/containerregistry/issues/9

Do we have any latest changes there?

**Comment by milosgajdos** [comment]
Closing. This is the wrong repo to ask this question. Please ask in https://github.com/distribution/distribution
