### ISSUE TITLE
Small grammar mistake in the registry docs

### ISSUE THREAD

**Issue by alzeebum** [distribution/distribution-library-image#178]
The page @ https://hub.docker.com/_/registry, under the "Quick reference (cont.)" section, there are several links titled "docs repo's".  These seem to be listings of different repos, and so all of these links should read "docs repos" without the apostrophe / single quote.  If the author isn't a native speaker of English, the apostrophe indicates a contraction like "repo is" or a possessive, neither of which makes sense.  "Repos" is the plural of "Repo".

**Comment by milosgajdos** [comment]
Closing. Docker Official Image readmes are maintained by Docker Inc., who owns that content. You'll have to open an issue in https://github.com/docker/hub-feedback
