### ISSUE TITLE
`linux/amd64` image is not pushed for `registry:3.0.0-rc.2` 

### ISSUE THREAD

**Issue by ialidzhikov** [distribution/distribution-library-image#181]
**What happened**:

`linux/amd64` image is not pushed for `registry:3.0.0-rc.2` 
```
% docker pull registry:3.0.0-rc.2 --platform linux/amd64
3.0.0-rc.2: Pulling from library/registry
no matching manifest for linux/amd64 in the manifest list entries
```

All previous versions support `linux/amd64`:
```
% docker pull registry:3.0.0-rc.1 --platform linux/amd64
3.0.0-rc.1: Pulling from library/registry
da9db072f522: Pull complete
c22c0d7190e7: Pull complete
b14c66978d04: Pull complete
be567d4e8079: Pull complete
916205650bfe: Pull complete
Digest: sha256:a2fe431494093c717403d475c03aefbc0dd959c3a087f432519ef072f52a16a4
Status: Downloaded newer image for registry:3.0.0-rc.1
docker.io/library/registry:3.0.0-rc.1

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview registry:3.0.0-rc.1
```

**What you expected to happen**:
To be able to pull` linux/amd64` image for `registry:3.0.0-rc.2`.
```
% docker pull registry:3.0.0-rc.2 --platform linux/amd64
```

**How to reproduce it (as minimally and precisely as possible)**:
Use 

```
% docker pull registry:3.0.0-rc.2 --platform linux/amd64
```

or open https://hub.docker.com/layers/library/registry/3.0.0-rc.2/images/sha256-35a1ea331fb2f3adf740d139190e4496a3e246f80db3d9f08d9f10ae1c5b84fd and see that linux/amd64 is not supported.

<img width="856" alt="Screenshot 2024-12-19 at 12 21 33" src="https://github.com/user-attachments/assets/43d2663a-74a3-43ce-9665-1b691781a5a0" />

**Comment by ialidzhikov** [comment]
cc @milosgajdos

**Comment by milosgajdos** [comment]
`arm64` image is missing, too for whatever reason. 

We'll have to wait for what Docker Inc. say. The only one on the inside is @thaJeztah who could make nudge someone there.

In the meantime please use the GHCR one or the one we own distribution/distribution:3.0.0-rc.2

**Comment by thaJeztah** [comment]
Hm... odd; wondering if it's stuck somewhere in a pipeline? Let me check if there's someone who has more insight

**Comment by ialidzhikov** [comment]
Now it works:
```
% docker pull registry:3.0.0-rc.2 --platform linux/amd64
3.0.0-rc.2: Pulling from library/registry
38a8310d387e: Already exists
774282edc096: Pull complete
5d55774b8a6d: Pull complete
553b04fa4677: Pull complete
3aa74f81ae76: Pull complete
Digest: sha256:e32c1e112183797463af147bb75a964f4d5c8244dbed462190c31d99346ebcd3
Status: Downloaded newer image for registry:3.0.0-rc.2
docker.io/library/registry:3.0.0-rc.2

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview registry:3.0.0-rc.2
```

<img width="860" alt="Screenshot 2024-12-19 at 14 39 14" src="https://github.com/user-attachments/assets/852476ee-3e72-4cca-b5a9-8dc30cd15054" />

**Comment by whalelines** [comment]
Each architecture has its own builder with its own queue and its own performance characteristics. It takes time for everything to work through and populated the image index.
