### ISSUE TITLE
Running as root user, why?

### ISSUE THREAD

**Issue by rmoriz** [distribution/distribution-library-image#34]
registry still runs as root user. (as of 2.6.0-rc.1)

"If a service can run without privileges, use USER to change to a non-root user."
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/user

**Comment by exdrunmeswt** [comment]
#34

**Comment by stevvooe** [comment]
Please submit a PR.

**Comment by milosgajdos** [comment]
Closing as wildly outdated.
