### ISSUE TITLE
using version 2.6 of the registry will not perform Deletes

### ISSUE THREAD

**Issue by hite77** [distribution/distribution-library-image#49]
I've set in the config.....
   storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /data/registry
    delete:
        enabled: true

I'm finding the sha, and performing delete, it either just details the manifest with a get, when I delete it says... {"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}

I've tried setting the environment variable for enabled delete, I've updated the config as shown above, and no matter what I try, it does not work.  

I want to be able to purge images that have not been accessed so that proxy will not fill up.  Currently we delete all the images, which causes the proxy to have to pull from artifactory again.

I have version 2.6.0 of the registry installed, and it proxies correctly, but no way to Delete.

Thanks 
hite77

**Comment by hite77** [comment]
I'm removing the files via the filesystem, and then calling garbage collection to remove the blob's.  But as far as I can tell the DELETE operations at least for manifests do not work.

**Comment by FrankIJskes** [comment]
Have you used the correct env settings?
See part of our docker-compose we use for our registry (we can delete our manifests with these settings):
<cut>
  environment:
    TZ: "Europe/Amsterdam"
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    **REGISTRY_STORAGE_DELETE_ENABLED: "true"**
<cut>

**Comment by milosgajdos** [comment]
Closing as outdated. please use the latest available stable release, also as mentioned above, make sure you use the correct config.
