### ISSUE TITLE
support arm64 system

### ISSUE THREAD

**Issue by longquan7** [distribution/distribution-library-image#54]
I was modify the Dockerfile the first line in order to support arm64.
Change "From alpine:3.5" to "From aarch64/alpine:3.5" that would support arm64 system. So How to use one Dockerfile to support different syatem than x86 and arm64.

**Comment by hrw** [comment]
I can build images on arm64. I can use ansible on arm64. I can not deploy from arm64 to other arm64 because registry image is x86-64 only ;(

**Comment by dansta** [comment]
I also want the registry running on arm64 architecture. I am currently trying to build some stuff for raspberry pi at home, and currently the workaround is building the image on all the swarm nodes or using images from dockerhub that are not maintained. Neither are reliable or preferred.

I'm sure I could fork the official registry repository and try to build it on my raspberry pi, but I believe official support would be more appreciated.

And from what I've read the rpi3 runs the Cortex A-53 which is arm 64bit, even though the kernel support is not there yet.

**Comment by hrw** [comment]
@dansta rpi3 can run arm64 kernel and userspace for quite long time.

**Comment by lag-linaro** [comment]
Any update on this issue?

The PR #74 submitted by @tianon looks to solve ARM64 and would ensure the happiness of quite a few users. :smile:

**Comment by tianon** [comment]
It's probably more palatable to the maintainers if we get it on Alpine 3.8
and thus a newer version of Go.  It'd be most ideal if we could get
officially published static binary releases, but that's a lot more work
than building here instead.

**Comment by lag-linaro** [comment]
Is there any reason why moving to Alpine 3.8 wouldn't 'just work'?

**Comment by milosgajdos** [comment]
Closing, as the latest v3 release does ship arm64 binaries https://hub.docker.com/layers/library/registry/3.0.0-rc.2/images/sha256-67ebb9d7db3096d61e15e6e06e18b7d581dc55d21aba8ed21677365e1079a76c
