### ISSUE TITLE
Registry issue with Aliyun OSS storage driver 

### ISSUE THREAD

**Issue by mytechathon** [distribution/distribution-library-image#55]
I setup a private registry with Aliyun OSS as the backend storage, and to save cost, I use internal Aliyun OSS endpoint instead of public endpoint, because it does not cost money to read/write object from/to oss in internal network.

The private registry works fine when pushing an image (through internet or internal network), because registry helps pushing image data to OSS.

However, when pulling an image (through internet), it does not work, because registry just tells docker client the URL of the objects in OSS, so that the docker client can directly pull the image object from Aliyun OSS. Since the URL given by registry is an internal URL, it is unreachable from internet, so the pull will fail.

The problem can be solved if we configure public OSS endpoint as storage driver for registry. However, this will bring additional cost, because Aliyun OSS costs money for in/out data through internet, and does not cost any if the data in/out through internal network.

So I think this is a bug of registry v2.6. when pulling, registry should also act like a delegator, who should pull image data from OSS to registry, and then pass through the data to docker client.

**Comment by lxiange** [comment]
This is configurable, please look at this page and disable the redirect:
https://docs.docker.com/registry/configuration/#redirect

**Comment by milosgajdos** [comment]
Closing as answered and outdated.
