### ISSUE TITLE
registry issue with ceph swift storage

### ISSUE THREAD

**Issue by planktonzp** [distribution/distribution-library-image#57]
when i create a local docker registry with ceph swift storage ,i find that the contianer is working but i cannot push any images to the registry,and when i check the logs of registry contauner and ceph rgw, i find lots of message like that 
`2017-08-10 00:04:30.744809 7f0c037fe700  1 ====== starting new request req=0x7f0c037f8710 =====`
`2017-08-10 00:04:30.748852 7f0c037fe700  1 ====== req done req=0x7f0c037f8710 op status=0 http_status=200 ======`
`2017-08-10 00:04:30.748922 7f0c037fe700  1 civetweb: 0x7f0bd80008c0: 172.16.3.92 - - [10/Aug/2017:00:04:30 +0800] "GET /swift/v1/docker_registry HTTP/1.1" 200 0 - distribution/v2.6.2`
`2017-08-10 00:04:30.749833 7f0c037fe700  1 ====== starting new request req=0x7f0c037f8710 =====`
`2017-08-10 00:04:30.751815 7f0c037fe700  1 ====== req done req=0x7f0c037f8710 op status=0 http_status=404 ======`
`2017-08-10 00:04:30.751869 7f0c037fe700  1 civetweb: 0x7f0bd80008c0: 172.16.3.92 - - [10/Aug/2017:00:04:30 +0800] "HEAD /swift/v1/docker_registry/files HTTP/1.1" 404 0 - distribution/v2.6.2`

and when i check registry container  by swiftclient ,i can find the contianer which is used by docker registry
`swift -A http://172.16.3.122:7480/auth/v1 -U sccc:swift -K 'uUACqbU7S7BoOWCwwv8TcHugrCbUjlImSYTjSk0y' list`
`docker_registry`

i am a  fresher , if anybody can help me , i'll be very appreciation

**Comment by milosgajdos** [comment]
Closing as SWIFT storage is no longer supported by distribution project: https://github.com/distribution/distribution/pull/3982
