### ISSUE TITLE
No support for eu-west-2

### ISSUE THREAD

**Issue by ocasta** [distribution/distribution-library-image#63]
The code change is in the master branch of the registry source. Any plans for a 2.6.3 or even a 2.7??

**Comment by quynhdang-vt** [comment]
Is there a vote button on issue, +1 for me

**Comment by ocasta** [comment]
While we wait for an official image I've built one from master. https://hub.docker.com/r/ocasta/docker-registry/

**Comment by quynhdang-vt** [comment]
Thank you!

**Comment by milosgajdos** [comment]
Closing, as wildly outdated. Please use the latest available V3 release which does have the west-2 region support
