### ISSUE TITLE
Any Chance of getting registry running on s390 

### ISSUE THREAD

**Issue by florianeichin** [distribution/distribution-library-image#73]
Is there any chance to get a registry container running on s390x architecture?

**Comment by milosgajdos** [comment]
Closing, as the latest v3 release does ship s390x binaries https://hub.docker.com/layers/library/registry/3.0.0-rc.2/images/sha256-67ebb9d7db3096d61e15e6e06e18b7d581dc55d21aba8ed21677365e1079a76c
