### ISSUE TITLE
Port 80 is normal, not port 80 returns 404

### ISSUE THREAD

**Issue by einsqing** [distribution/distribution-library-image#79]
Port 80 is normal, not port 80 returns 404
![qq20180927-114938](https://user-images.githubusercontent.com/7685948/46122475-710fd980-c24b-11e8-997e-75d266908cc6.png)

**Comment by martin2110** [comment]
The hostname and port are part of a docker tag.  the image without the 80 does not exist. If you wanted this to work you could do:
```
docker tag  docker.oneqing.com:80/root/test:5 docker.oneqing.com/root/test:5
docker push docker.oneqing.com:80/root/test:5
```
Then your pull should work.

**Comment by milosgajdos** [comment]
Closing as wildly outdated.
