### ISSUE TITLE
ppc64le support in multi-arch image

### ISSUE THREAD

**Issue by harche** [distribution/distribution-library-image#95]
The multi-arch image for docker registry, https://hub.docker.com/_/registry, doesn't have the reference to `ppc64le` image. 

We will like to add the support for `ppc64le` architecture as well for this image.

**Comment by clnperez** [comment]
Can you submit a patch to the official images repo to add it? 

https://github.com/docker-library/official-images/blob/master/library/registry

**Comment by milosgajdos** [comment]
Please use the latest available v3 release image: https://hub.docker.com/layers/library/registry/3.0.0-rc.2/images/sha256-67ebb9d7db3096d61e15e6e06e18b7d581dc55d21aba8ed21677365e1079a76c

Closing.
