### ISSUE TITLE
Can not delete repo from registry

### ISSUE THREAD

**Issue by hoangn5** [distribution/distribution-library-image#98]
Hi all,

I'm trying to delete repo from registry to free up storage space in my system
please take a look at this
Issues with docker registry API and garbage-colle
https://forums.docker.com/t/issues-with-docker-registry-api-and-garbage-collect/77510

Thanks,
Hoang Nguyen

**Comment by hoangn5** [comment]
Or any one know how to propely delete a single repository/image in registry to free up system storage

**Comment by yurygoncharuk** [comment]
Hi guys,
I have the same issue.
Any suggestions how to fix it?

**Comment by pada57** [comment]
Hello

i found APIs to  delete images from registry but not any for deleting repository. only way i found to delete, was to go on container itself and delete folders manually

delete image api : https://docs.docker.com/registry/spec/api/#deleting-an-image

NO for repository ??

is it planned to add support for it ?

thanks a lot in advance

**Comment by pada57** [comment]
> Or any one know how to propely delete a single repository/image in registry to free up system storage

to free up just delete image : https://docs.docker.com/registry/spec/api/#deleting-an-image
and then running garbage collector on registry

only think as i mentioned did not find way to properly delete repository from API
